# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'baseApp' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!
	pod 'TextFieldEffects'
	pod 'Alamofire', '~> 4.5'
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'
end
